variables:
 IMAGE: "sso"
 TAG: "date +%Y%m%d%H%M"

before_script:
 - mkdir src
 - mkdir src/sso
 - mv -f common src/sso
 - mv -f conf src/sso
 - mv -f controllers src/sso
 - mv -f models src/sso
 - mv -f routers src/sso
 - mv -f swagger src/sso
 - mv -f tests src/sso
 - mv -f vendor src/sso
 - mv -f main.go src/sso

build_image:
 script:
  - export GOPATH=$PWD
  - cd src/sso/
  - go build main.go
  - cd ../../
  - echo `git log | head -1 | cut -d ' ' -f2` > ./Manifest
#  - IMAGE=sso
#  - TAG=`date +%Y%m%d%H%M`
  - docker build -t $IMAGE:$CI_PIPELINE_ID .
  - docker tag $IMAGE:$CI_PIPELINE_ID img.reg.3g:15000/$IMAGE:$CI_PIPELINE_ID
  - docker push img.reg.3g:15000/$IMAGE:$CI_PIPELINE_ID