ymltest:
 stage: test
 script:
  - echo $(dirname "$PWD")
  - PARENTDIR=$(dirname "$PWD")
  - GOPATH=$PARENTDIR"/gopath"
  - SRC=$GOPATH"/src"
  - if [ ! -f "$GOPATH" ]
  - then
  - echo "file not exists1"
  - else
  - echo "file exists1"
  - fi
  - if [ -f "$GOPATH" ]
  - then
  - echo "gopath exists2"
  - else
  - echo "gopath not exists2"
  - fi