ymltest:
 stage: test
 script:
  - echo $(dirname "$PWD")
  - PARENTDIR=$(dirname "$PWD")
  - GOPATH=$PARENTDIR"/gopath"
  - SRC=$GOPATH"/src"
  - if [ ！-d "$GOPATH" ]
  - then
  - mkdir $GOPATH
  - else 
  - echo "gopath exists"$GOPATH
  - fi
  - if [ ！-d "$SRC" ]
  - then
  - mkdir $SRC
  - else
  - echo "src exists"$SRC
  - fi
  - export GOPATH=$GOPATH
  - echo "gopath="$GOPATH
  - echo "pwd="$PWD
  - ls
  - cd ..
  - pwd
  - cp -r $PWD $SRC
  - cd $SRC
  - pwd