variables:
  IMAGE: "sso"
  DATA: "{\"image\":\"img.reg.3g:15000/$IMAGE:$CI_PIPELINE_ID\"}"
stages:
- deploy
golang_deploy:
  stage: deploy
  script:
    - PARENTFOLDER=$(dirname "$PWD")
    - GOPATH=$PARENTFOLDER"/gopath"
    - GOPATHSRC=$PARENTFOLDER"/gopath/src"
    - if [ -f "$GOPATH" ] 
    - then 
          echo "gopath exists"
    - else 
          mkdir $GOPATH 
    - fi
    - if [ -f "$GOPATHSRC" ]
    - then 
    -    echo "gopath src exists"
    -    rm -rf $GOPATHSRC
    -    mkdir $GOPATHSRC 
    - else 
    -    mkdir $GOPATHSRC 
    - fi
    - export GOPATH=$GOPATH
    - echo "gopath="$GOPATH
    - PROJECTPATH=$GOPATHSRC"/"${PWD##*/}
    - echo $PROJECTPATH
    - cp -r $PWD $GOPATHSRC
    # - cd $GOPATHSRC
    # - ls -la
    - cd $PROJECTPATH
    - echo "----------$PROJECTPATH-------------"
    - ls -la
    - echo "-------------go bulid-------------"
    - go build main.go
    - docker build -t $IMAGE:$CI_PIPELINE_ID .
    - docker tag $IMAGE:$CI_PIPELINE_ID img.reg.3g:15000/$IMAGE:$CI_PIPELINE_ID
    - docker push img.reg.3g:15000/$IMAGE:$CI_PIPELINE_ID
    
    