ymltest:
 stage: test
 script:
  - echo $(dirname "$PWD")
  - PARENTDIR=$(dirname "$PWD")
  - GOPATH=$PARENTDIR"/gopath"
  - SRC=$GOPATH"/src"
  - rm -rf $GOPATH/zxy
  - '[ ! -f "$GOPATHSRC" ] && mkdir $GOPATH/zxy'
  - ls -la $GOPATH/zxy