ymltest:
 stage: test
 script:
  - echo $(dirname "$PWD")
  - PARENTDIR=$(dirname "$PWD")
  - GOPATH=$PARENTDIR"/gopath"
  - SRC=$GOPATH"/src"
  - rm -rf $GOPATH
  - mkdir "$GOAPTH"
  - if [ ! -d "$GOPATH" ]
  - then
  -    mkdir "$GOAPTH"
  - else 
  -    echo "gopath exists"$GOPATH
  - fi
  - if [ ! -d "$SRC" ]
  - then
  -     mkdir $SRC
  - else
  -    echo "src exists"$SRC
  - fi
  - export GOPATH=$GOPATH
  - echo "gopath="$GOPATH
  - echo "pwd="$PWD
  - ls
  - cd ..
  - pwd
  - ls
  - cd gopah
  - pwd
  - ls
  - cd src
  - pwd
  - ls
  - cd ../../sso
  - cp -r $PWD $SRC
  - cd $SRC
  - pwd
  - ls
