variables:
  IMAGE: "sso"
  DATA: "{\"image\":\"img.reg.3g:15000/$IMAGE:$CI_PIPELINE_ID\"}"
stages:
- deploy
golang_deploy:
  stage: deploy
  script:
    - PARENTFOLDER=$(dirname "$PWD")
    - GOPATH=$PARENTFOLDER"/gopath"
    - GOPATHSRC=$PARENTFOLDER"/gopath/src"
    # - if [ -f "$GOPATH" ]
    # - then
    #       echo "gopath exists"
    # - else
    #       mkdir $GOPATH
    # - fi
    - rm -rf $GOPATHSRC
    - if [ -f "$GOPATHSRC" ]
    - then
    -    echo "gopath src exists"
    -    rm -rf $GOPATHSRC
    -    mkdir $GOPATHSRC
    - else
    -    echo "gopath src not exists"
    -    mkdir $GOPATHSRC
    - fi