variables:
 IMAGE: "sso"
# 此处无法定义TAG为时间戳:  `date +%Y%m%d%H%M`,不执行反引号命令

before_script:
 - mkdir src
 - mkdir src/sso
 - mv -f common src/sso
 - mv -f conf src/sso
 - mv -f controllers src/sso
 - mv -f models src/sso
 - mv -f routers src/sso
 - mv -f swagger src/sso
 - mv -f tests src/sso
 - mv -f vendor src/sso
 - mv -f main.go src/sso

build_image:
 script:
  - pwd
  - ls -a
  - export GOPATH=$PWD
  - cd src/sso/
  - go build main.go
  - cd ../../
  - pwd
  - ls -a
  - echo `git log | head -1 | cut -d ' ' -f2` > ./Manifest
#  - IMAGE=sso
  - TAG=`date +%Y%m%d%H%M`
  - docker build -t $IMAGE:$TAG .
  - docker tag $IMAGE:$TAG img.reg.3g:15000/$IMAGE:$TAG
  - docker push img.reg.3g:15000/$IMAGE:$TAG
