variables:
  IMAGE: "sso"
stages:
- deploy
golang_deploy:
  stage: deploy
  script:
    - PARENTFOLDER=$(dirname "$PWD")
    - GOPATH=$PARENTFOLDER"/gopath"
    - GOPATHSRC=$PARENTFOLDER"/gopath/src"
    - PROJECTNAME=${PWD##*/}
    - PROJECTPATH=$GOPATHSRC"/"${PROJECTNAME}
    - if [ ! -d "$GOPATH" ]; then mkdir $GOPATH; else echo "gopath exists"$GOPATH; fi
    - if [ ! -d "$GOPATHSRC" ]; then mkdir $GOPATHSRC; else echo "gopath exists"$GOPATH; fi
    - export GOPATH=$GOPATH
    - echo "GOPATH="$GOPAHT
    - cp -r $PWD $GOPATHSRC
    - cd $PROJECTPATH
    - echo "----------$PROJECTPATH-------------"
    - ls -la
    - echo "-------------go bulid-------------"
    - go build main.go
    - echo `git log | head -1 | cut -d ' ' -f2` > manifest
    - TAG=`date +%Y%m%d%H%M`
    - docker build -t $IMAGE:$TAG .
    - docker tag $IMAGE:$TAG img.reg.3g:15000/$IMAGE:$TAG
    - docker push img.reg.3g:15000/$IMAGE:$TAG