ymltest:
 stage: test
 script:
  - echo $(dirname "$PWD")
  - PARENTDIR=$(dirname "$PWD")
  - GOPATH=$PARENTDIR"/gopath"
  - SRC=$GOPATH"/src"
  - if [ ! -f "$GOPATH" ]
  - then
  - echo "file not exists"
  - fi
  - if [ -f "$GOPATH" ]
  - then
  - echo "gopath exists"
  - fi