variables:
  IMAGE: "gitlab-ci-demo"
  DATA: "{\"image\":\"img.reg.3g:15000/$IMAGE:$CI_PIPELINE_ID\"}"
stages:
- test
#- build
#- deploy
golang_test:
  stage: test
  script:
    - PARENTFOLDER=$(dirname "$PWD")
    - GOPATH=$PARENTFOLDER"/gopath"
    - GOPATHSRC=$PARENTFOLDER"/gopath/src"
    - if [ -f "$GOPATH" ] 
    - then 
          echo "gopath exists"
    - else 
          mkdir $GOPATH 
    - fi
    - if [ -f "$GOPATHSRC" ]
    - then 
    -    echo "gopath src exists"
    -    rm -rf $GOPATHSRC
    -    mkdir $GOPATHSRC 
    - else 
    -    mkdir $GOPATHSRC 
    - fi
    - export GOPATH=$GOPATH
    - echo "gopath="$GOPATH
    - pwd
    - ls
    - cd ..
    - pwd
    - cd src
    - ls
    - cd ../sso
    - cp -r $PWD $GOPATHSRC
    - cd $GOPATHSRC
    - pwd
    - ls
    - ls -la
    - echo $GOPATHSRC"/"${PWD##*/}