variables:
  IMAGE: "sso"
  DATA: "{\"image\":\"img.reg.3g:15000/$IMAGE:$CI_PIPELINE_ID\"}"
stages:
- deploy
golang_deploy:
  stage: deploy
  script:
    - PARENTFOLDER=$(dirname "$PWD")
    - GOPATH=$PARENTFOLDER"/gopath"
    - GOPATHSRC=$PARENTFOLDER"/gopath/src"
    - PROJECTNAME=/"${PWD##*/}
    - PROJECTPATH=$GOPATHSRC"/"${PROJECTNAME}
    - if [ ! -d "$GOPATH" ]; then mkdir $GOPATH; else echo "gopath exists"$GOPATH; fi
    - if [ ! -d "$GOPATHSRC" ]; then mkdir $GOPATHSRC; else echo "gopath exists"$GOPATH; fi
    - export GOPATH=$GOPATH
    - cd ..
    - echo "$PROJECTNAME"
    - echo $PROJECTPATH 
    #- mv $PROJECTNAME $PROJECTPATH