variables:
  IMAGE: "gitlab-ci-demo"
  DATA: "{\"image\":\"img.reg.3g:15000/$IMAGE:$CI_PIPELINE_ID\"}"
stages:
- test
#- build
#- deploy
golang_test:
  stage: test
  script:
    - PARENTFOLDER=$(dirname "$PWD")
    - gopath=$PARENTFOLDER"/gopath"
    - gopathsrc=$PARENTFOLDER"/gopath/src"
    - if [ -f "$gopath" ] 
    - then 
          echo "gopath exists"
    - else 
          mkdir $gopath 
    - fi
    - if [ -f "$gopathsrc" ]
    - then 
    -    echo "gopath src exists"
    - else 
    -    mkdir $gopathsrc 
    - fi
    - export GOPATH=$gopath
    - echo "-----------------------------------gopath="$gopathsrc
    - echo $PWD
    #- cp -r $PWD $GOPATHSRC
    #- cd $GOPATHSRC
    #- ls -la
    # - echo $CI_PIPELINE_ID
    # - echo $CI_JOB_ID
    # - echo $CI_COMMIT_SHA
    
    #- go test ./...