ymltest:
 stage: test
 script:
  - echo $(dirname "$PWD")
  - PARENTDIR=$(dirname "$PWD")
  - GOPATH=$PARENTDIR"/gopath"
  - SRC=$GOPATH"/src"
  - mkdir $GOPATH/zxy
  #- rm -rf $GOPATH/zxy
  - 'if [ ! -f "$GOPATH/zxy" ]; then echo "file zxy not exists"; else echo "file zxy exists"; fi'