ymltest:
 stage: test
 script:
  - echo $(dirname "$PWD")
  - PARENTDIR=$(dirname "$PWD")
  - GOPATH=$PARENTDIR"/gopath"
  - SRC=$GOPATH"/src"
  - mkdir $GOPATH/zxy
  - 'if [ ! -f "$GOPATH/zxy" ];then echo "file zxy not exists1";else echo "file zxy exists1";fi'