ymltest:
 stage: test
 script:
  - echo $(dirname "$PWD")
  - PARENTDIR=$(dirname "$PWD")
  - GOPATH=$PARENTDIR"/gopath"
  - SRC=$GOPATH"/src"
  - rm -rf $GOPATH/zxy
  - mkdir $GOPATH/zxy
  #- rm -rf $GOPATH/zxy
  - if [ -d $GOPATH"/zxy" ];then echo "file zxy exists";else echo "file zxy not exists";fi
  - (if [ -d "$GOPATH/zxy" ];then echo "file zxy exists";else echo "file zxy not exists";fi)