variables:
  IMAGE: "gitlab-ci-demo"
  DATA: "{\"image\":\"img.reg.3g:15000/$IMAGE:$CI_PIPELINE_ID\"}"
stages:
- test
#- build
#- deploy
golang_test:
  stage: test
  script:
    - SSO=$PWD
    - GOPATH=$SSO"/gopath"
    - GOPATHSRC=$SSO"/gopath/src"
    - if [ -f "$GOPATH" ] ;then echo "gopath exists"; else mkdir $gopath ;fi
    - if [ -f "$GOPATHSRC" ] ;then echo "gopath exists"; else mkdir $gopath ;fi
    - export GOPATH=$GOPATH
    - echo $GOPATH
    - cp $SSO $GOPATHSRC
    - cd $SSO
    - ls -la