ymltest:
 stage: test
 script:
  - echo $(dirname "$PWD")
  - PARENTDIR=$(dirname "$PWD")
  - GOPATH=$PARENTDIR"/gopath"
  - SRC=$GOPATH"/src"
  - if [ ! -f "$GOPATH/zxy" ];then echo "file zxy not exists1";else echo "file zxy exists1";fi
  - if [ ! -f "$GOPATH" ];then echo "file gopath not exists1";else echo "file gopath exists1";fi
  - if [ ! -f "$GOPATH" ]
  - then 
  - echo "return file gopath not exists1"
  - else 
  - echo "return file gopath exists1"
  - fi