ymltest:
 stage: test
 script:
  - echo $(dirname "$PWD")
  - PARENTDIR=$(dirname "$PWD")
  - GOPATH=$PARENTDIR"/gopath"
  - SRC=$GOPATH"/src"
  - if [ -f "$GOPATH" ]
  - then
      echo "gopath exists"$GOPATH
  - else 
      mkdir $GOPATH
  - fi
  - if [ -f "$SRC" ]
  - then
    echo "src exists"$SRC
  - else
     mkdir $SRC
  - fi
  - export GOPATH=$GOPATH
  - echo "gopath="$GOPATH
  - echo "pwd="$PWD
  - cp -r $PWD $SRC
  - cd $SRC
  - pwd