variables:
  IMAGE: "gitlab-ci-demo"
  DATA: "{\"image\":\"img.reg.3g:15000/$IMAGE:$CI_PIPELINE_ID\"}"
  GOPATH: "$GOPATH/gopath"
stages:
- test
#- build
#- deploy
golang_test:
  stage: test
  script:
    - echo $GOPATH