ymltest:
 stage: test
 script:
  - echo $(dirname "$PWD")
  - PARENTDIR=$(dirname "$PWD")
  - GOPATH=$PARENTDIR"/gopath"
  - SRC=$GOPATH"/src"
  - if [ ! -f "$GOPATH" ]
  - then
  - mkdir $GOPATH
  - else 
  - echo "gopath exists"$GOPATH
  - fi