variables:
  IMAGE: "gitlab-ci-demo"
  DATA: "{\"image\":\"img.reg.3g:15000/$IMAGE:$CI_PIPELINE_ID\"}"
  GOPATH: "/usr/local/gopath"
stages:
- test
#- build
#- deploy
golang_test:
  stage: test
  script:
    - echo $CI_PIPELINE_ID
    - echo $CI_JOB_ID
    - echo $CI_COMMIT_SHA
    - echo $PWD
    - echo $GOPATH
    #- go test ./...